### ISSUE TITLE
Possible Issue With Combobox?

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/GrapheneForms#1]
Note: Not sure the cause of this issue -- test case below may not actually cause problem indicated.  Possible issue related to duplicate (empty?) values in array of options.

The following form definition causes the form to lock up.  (Running against latest code at https://docs.escherlabs.com/GrapheneForms/builder.html as of 10/10/19, so may not reflect latest actual development code)

The combobox is pulling from: `https://raw.githubusercontent.com/timcortesi/dummyjson/master/exp_types.json` which contains slightly less than 400 rows.  It is valid JSON, and the same form works fine if the combo box is changed to a basic select.

```json
{
	"fields": [
		{
			"type": "smallcombo",
			"label": "My Stuff",
			"name": "my_stuff",
			"display": "",
			"options": [
				{
					"label": "",
					"type": "optgroup",
					"path": "https://raw.githubusercontent.com/timcortesi/dummyjson/master/exp_types.json"
				}
			]
		}
	]
}
```

**Comment by alikemaltanriverdi** [comment]
This issue also affects the input box. They're all created with the display width of 1 column and their width is reset to 1 every time I add or edit something
